=== {learning-goals}


// tag::DE[]
Dieser Block soll TODO

[[LZ-5-1]]
==== LZ 5-1: Die Herausforderungen im Betrieb von Microservices verstehen
TODO

[[LZ-5-2]]
==== LZ 5-2: Die Telemetrie-Bausteine Logs, Metriken und Traces verstehen
* Die TN kennen die Eigenschaften der Telemetrie-Bausteine Logs, Metriken und Traces
* Die TN wissen, wie sie die verschiedenen Arten von Metriken nutzen und wie man sie aggregieren kann
* Die TN wissen, wie Traces aufgebaut sind, z.B. das Modell von OpenTelemetry


[[LZ-5-3]]
==== LZ 5-3: Telemetrie nutzen, um kritische Geschäftsfälle zu monitoren
* Die TN verstehen, dass sie Telemetriedaten unterschiedlich auswerten müssen: Geschäftsmetriken ("ist etwas kaputt?") und Analysedaten ("was ist kaputt?")
* Die TN verstehen, wie man für die wichtigsten Use Cases eines Systems betriebliche Anforderungen (z.B. Verfügbarkeit, Latenz, usw.) definiert, z.B. mithilfe von Service Level Objectives (SLOs)
* Die TN kennen unterschiedliche Möglichkeiten die betrieblichen Anforderungen von den wichtigsten Use Cases zu monitoren, z.B. mit synthetischen Clients, Enduser-Monitoring, Loadbalancer- oder Service-Metriken (SLIs).
* Die TN kennen das Konzept des Error Budgets
* Die TN wissen, wie man Alarme definieren kann, sodass Probleme rechtzeitig erkannt werden können und gleichzeitig keine Fehlalarme ausgelöst werden

[[LZ-5-4]]
==== LZ 5-4: Major Incident Response und Post-Mortems
* Die TN kennen Beispiele, wie man mithilfe von Logs, Metriken und Traces Probleme analysieren kann
* Die TN kennen die Kernpunkte eines Major Incident Prozesses
* Die TN kennen Möglichkeiten, wie man Major Incident Prozesse einüben kann, z.B. Game Days oder Fire Drills


// end::DE[]

// tag::EN[]
[[LG-5-1]]
==== LG 5-1: TBD
tbd.

[[LG-5-2]]
==== LG 5-2: TBD
tbd.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
